### ISSUE TITLE
FR: Sharepoint support

### ISSUE THREAD

**Issue by mansalvunict** [nico9889/OneNote2XournalppAddon#5]
When I tried to export one note page on my university domain UNI..-sharepoint/... the extension doesn't recognize the one note page, I tried to follow instructions but doesn't  work :(

**Comment by nico9889** [comment]
Hi, thank you for reaching out.
The addon is restricted [on purpose](https://github.com/nico9889/OneNote2XournalppAddon/blob/a4510ef63a772a0e9d17f89485f56d4bf2865280/public/manifest.json#L15-L25) only on OneDrive/OneNote domains both for technical and privacy reason:
* it works by injecting a little script in the page, injecting the script in non tested pages may cause unexpected issues;
* the little script can read and/or modify the content of the page, it would be a problem if it could read any page a user is visiting.

This is a standard behaviour for any addon which requires to access the page data (in this case text, strokes and images). If you have any concern about that you can inspect the code in this repository or ask someone else if this is not your kind of stuff.

There's a second issue: the addon relies heavily on the page source and permissions which may change in SharePoint.

I can try to add your university domain to the allowed domain list but I will need your help for testing.

I can send you a custom build and detailed instructions on how to install it, with a bit of luck it will work without additional changes.

If you are ok with that I need to know:
* your university domain, in particular when you open the SharePoint page;
* if you are using Firefox or Chrome (or any derivative).

You can also send these information by email to cws@nico9889.me if you don't want to share publicly.

**Comment by nico9889** [comment]
Good news!
I tried with my university account and I discovered that I have access to SharePoint and with a few changes I've been able to export the note I created.
Furthermore, the SharePoint domains seems to follow a standard pattern (university-name[dot]sharepoint[dot]com) which allows me to support all the domain variants all at once.
I'm quite confident so I've already pushed an update both for Firefox and Chrome, please check your your addon version (should be 1.2.1) and give it a try.
Feel free to re-open this issue if this isn't solved for you or the domain pattern doesn't cover your's university one.

Edit: please note that it may require some times before the update appears on Google Web Store due to the revision time.

**Comment by mansalvunict** [comment]
Great!  I'm trying now... Thanks U
