### ISSUE TITLE
math elements are not being exported

### ISSUE THREAD

**Issue by kpodurgiel** [nico9889/OneNote2XournalppAddon#7]
Hi there!
Awesome job with the extension! Sadly, it doesn't export math nodes. Also, when math nodes are present on the page, the extension won't export anything, and no error is shown to the user.

I've just opened a pull request (#6) with a simple fix for a condition that was breaking while handling the text nodes, but I'm not familiar enough with the Xournal specs or this project to implement math nodes conversion.

**Comment by nico9889** [comment]
Hi, 
I'm not really a OneNote user, I made this addon mostly for notes shared with me which only has math written by hand, so math blocks slipped under the radar.

I did a bit of investigation on how Xournal++ handle maths: when you input a LaTeX math expression it converts it immediatly into a PDF binary, it encodes it into base64 and it bundle it inside of the output XOPP file (which is XML).
The LaTeX input is saved into an attribute for later editing.

The end result looks like this:
```xml
<teximage text="(u,v) \in E \text{ then } (u,v) \not\in\bar{E}" left="88.15523" top="87.925059" right="215.48323" bottom="108.55306"> redacted base64 pdf because it's too long </teximage>
```
Where:
* `text`: is the original LaTeX text;
* `left`, `right`, `bottom`, `up`: are attributes used for position and dimension of the rendered image.

In my opinion it's a bit weird having a raw PDF, but I assume it's for performance reason, to avoid re-rendering LaTeX everytime a file is open.

I did some experiment manually editing the XML and tried to replace the raw PDF with an arbitrary PNG (still encoded as base64), it looks like Xournal++ is able to load and render it correctly, which is good since it's probably easier to convert MathML from OneNote to PNG instead of PDF.

To convert MathML to LaTeX I found this package https://github.com/asnunes/mathml-to-latex, which can be used to populate the `text` attribute.

Right now I'm stuck at converting MathML to PDF/PNG.

To convert it to PDF I found the MathJax package, but it's hard to load with TypeScript since it lacks proper type definitions (`@types/mathjax` is referring to v2, the last stable is v3, I was looking into using v4 since v3 has an unsolved vulnerability).

So I tried with a manual approach:
* convert MathML to SVG (it seems that MathML can be transplanted from HTML to SVG);
* load the SVG as an Image (for some reason browsers seems to refuse to do that, but they can load the SVG correctly if saved as a file);
* Draw the Image into a Canvas to save it as base64 encoded PNG (which is supported by Xournal++).

https://github.com/nico9889/OneNote2XournalppAddon/blob/7d65c82f00d41b532282512a600dfb763e6cf840/src/converter/converter.ts#L239-L310

Please note that even position and/or dimensions are currently wrong, I haven't been able to render a proper image but I can see the output page is way too large than is should be and I'm missing the usage of offsets passed as a function argument.

I feel like I'm near to a solution, but I'm currently stuck at this point.

**Comment by kpodurgiel** [comment]
> In my opinion it's a bit weird having a raw PDF, but I assume it's for performance reason, to avoid re-rendering LaTeX everytime a file is open.

LaTeX isn't bundled with Xournal, users have to install a TeX distribution separately ([source](https://xournalpp.github.io/guide/tools/latex/)). This is probably why it's rendered and embeded – so that everyone can see prerendered content.

I got good results using `html2canvas` on equations rendered by KaTeX. I quickly tested it on the [katex.org](https://katex.org/) page after pasting [html2canvas.min.js](https://html2canvas.hertzen.com/dist/html2canvas.min.js), and using the belowe script on a element containing the entire equation:

```js
html2canvas($0).then(canvas => {
    const win = window.open("", "Canvas", "toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=yes,resizable=yes,width=600,height=600");
    win.document.body.appendChild(canvas);
})
```

This opens a window with a canvas containing the last selected HTML element. It would require parsing the LaTeX equation obtained from the MathML, which feels like reinventing the wheel, but I don't have a better idea at the moment. I've tested `html2canvas` on OneNote's `<math>` element, but it was ugly. This approach results in a raster image, but it's better than nothing.

It's possible that your issues are related to the use of `<foreignObject>`. [This thread](https://github.com/mathjax/MathJax/issues/2385#issuecomment-1546881833) might contain a solution to the problem with MathJax and TypeScript. It would be awesome, should this work, because we would only need to pass MathML to get a SVG.

**Comment by nico9889** [comment]
> I got good results using `html2canvas` on equations rendered by KaTeX. I quickly tested it on the [katex.org](https://katex.org/) page after pasting [html2canvas.min.js](https://html2canvas.hertzen.com/dist/html2canvas.min.js), and using the belowe script on a element containing the entire equation:
> 
> ```js
> html2canvas($0).then(canvas => {
>     const win = window.open("", "Canvas", "toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=yes,resizable=yes,width=600,height=600");
>     win.document.body.appendChild(canvas);
> })
> ```

I already tried `html2canvas` by installing it via npm, unfortunately trying on Firefox I got some weird `SecurityError` exception :(

> [This thread](https://github.com/mathjax/MathJax/issues/2385#issuecomment-1546881833) might contain a solution to the problem with MathJax and TypeScript. It would be awesome, should this work, because we would only need to pass MathML to get a SVG.

I knew about that thread, since you mentioned it I decided to try again and after a couple of hours of trial and error I finally got it working!

![Image showing math export result](https://github.com/nico9889/OneNote2XournalppAddon/assets/1190635/30d05eda-c635-47e7-9c54-752135bbce7d)

(don't mind the content, it has no sense, I'm not used to OneNote's math editor and I wrote some garbage just to test the behavior)

I had to do some hacky scaling to make the text look decent, but now it's working.
The text looks a bit stretched, probably it's because of some difference between fonts used by OneNote and MathJax.

I already pushed the changes in the `mathml-conversion` branch. If you have any notes with more complex math, would it be possible for you to test it? I expect the normal text to overlap since the addon tries to emulate the text wrapping behavior of the browser and I never got it correctly.

Edit: I'm only noticing now that some symbols are missing :(

**Comment by nico9889** [comment]
> I had to do some hacky scaling to make the text look decent, but now it's working. The text looks a bit stretched, probably it's because of some difference between fonts used by OneNote and MathJax.

> Edit: I'm only noticing now that some symbols are missing :(

Hi, I spent some time to improve image scaling and positioning, now the image should be rendered with correct proportions and in the right position (before it was moved a bit lower).

Previously symbols were missing because of improper scaling of the rendered image was bigger than the canvas, and the canvas had a fixed wrong size.

I added 3 user selectable scaling values (x1, x2, x4), this is to permit the final user to choose from blurrier text (lower file size, this may be useful on document with a lot of math) to crispier text.

One last remaining thing is to change the text color with dark pages (both normal and math text), I'll check this out later.

Please let me know if the changes works for you when you have some time.

**Comment by kpodurgiel** [comment]
Awesome job!
![image](https://github.com/nico9889/OneNote2XournalppAddon/assets/54937947/3af685ff-7eae-4664-92e5-7c95f9d8ecc8)

In this example equations look a bit stretched, but I don't mind as they look more correct (the lines above letters are of correct length), and I could probably regenerate the TeXs in Xournal. 
![image](https://github.com/nico9889/OneNote2XournalppAddon/assets/54937947/7fa1ae8c-6846-4efe-a344-5bb39de62ba7)
(Don't mind the pluses... they are regular text, as I probably gave up fighting with the equations in OneNote, and left them that way)

I tested it also on a more complex equation ([from Wikipedia](https://en.wikipedia.org/wiki/Fourier_series)):
![image](https://github.com/nico9889/OneNote2XournalppAddon/assets/54937947/cd8a3c07-9868-424d-b428-cbb9eb5202be)

**Comment by nico9889** [comment]
Nice! One last question before closing this issue

> In this example equations look a bit stretched, but I don't mind as they look more correct (the lines above letters are of correct length), and I could probably regenerate the TeXs in Xournal. ![image](https://private-user-images.githubusercontent.com/54937947/344695168-7fa1ae8c-6846-4efe-a344-5bb39de62ba7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NDMxMzMsIm5iZiI6MTcxOTg0MjgzMywicGF0aCI6Ii81NDkzNzk0Ny8zNDQ2OTUxNjgtN2ZhMWFlOGMtNjg0Ni00ZWZlLWEzNDQtNWJiMzlkZTYyYmE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDE0MDcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3ZmJhY2IwZDE5MWE4YTA4ODdjZTFlZWMxMjdjYTYzMDA5NzUwMTcyNTQ5YTFlMTUxYTVjOTdlN2UxNGFhNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MlBpfIdDib1cEsucGpMZJ3pQpzkqojZwqMuDJZQSdHY) (Don't mind the pluses... they are regular text, as I probably gave up fighting with the equations in OneNote, and left them that way)

Is this example generated from Google Chrome or Firefox? I noticed some difference in text placement between the two browsers, in my case Firefox shifts equations a few pixels **down**, I tried to apply a fix (`-(fontSize / 2)` in this line)
https://github.com/nico9889/OneNote2XournalppAddon/blob/04f5366dae36ea2956294a63dbae58e175cd43f2/src/converter/converter.ts#L326
but it seems that now it's Chrome with equations shifted a few pixel **up**.

I don't think I will fix this because there's no API (a few workarounds exist but I'm worried about the reliability) to get the browser the extension is running in, but I think it's good to know for future reference.

**Comment by kpodurgiel** [comment]
I use Google Chrome. Firefox indeed does it better:
![image](https://github.com/nico9889/OneNote2XournalppAddon/assets/54937947/ad91f1ef-e87a-4ccd-b9f3-810651badf67)

Many thanks for your work! 👏
